// ui/src/components/Header.svelte
<script lang="ts">
	import {
		FURNITURES,
		IS_CART_OPEN,
		IS_MENU_MINIMIZED,
		SHOWFURNITURES,
		CART,
		OWNEDITEMS,
		IS_OWNEDITEMS_OPEN
	} from '@store/stores'

	let selected: number = -1
	let scrollableElement: HTMLElement

	function scrollHorizontally(e) {
		e = window.event || e
		var delta = Math.max(-1, Math.min(1, e.wheelDelta || -e.detail))
		scrollableElement.scrollLeft -= delta * 50 // Multiplied by 40
		e.preventDefault()
	}

	let showSearch: boolean = false
	let searchTerm: string = ''

	$: {
		if (searchTerm.length > 0) {
			let allFurnitureItems = null
			if (selected == -1) {
				allFurnitureItems = $FURNITURES.flatMap(furniture => furniture.items);
			} else {
				allFurnitureItems = $FURNITURES[selected].items
			}

			const filteredFurnitureItems = allFurnitureItems.filter(furniture => furniture.label.toLowerCase().includes(searchTerm.toLowerCase()))
			$SHOWFURNITURES = { category: "Search Results", items: filteredFurnitureItems }
		} else {
			if (selected === -1) {
				const allFurnitureItems = $FURNITURES.flatMap(furniture => furniture.items);
				$SHOWFURNITURES = { category: "All Objects", items: allFurnitureItems }
			} else {
				$SHOWFURNITURES = $FURNITURES[selected]
			}
		}
	}


</script>

<div
	class="w-full h-full overflow-y-visible flex flex-row gap-2 items-end flex-nowrap"
>
	<button class="h-[4.5rem] {showSearch?"w-fit" : "w-[5rem] aspect-square"} bg-[color:var(--color-secondary)] flex flex-row gap-2 items-center"

	>
		<button
			class="h-[4.5rem] w-[4.5rem] aspect-square bg-[color:var(--color-secondary)] flex flex-row gap-2 items-center justify-center"
		on:click={() => {
			showSearch = !showSearch
			if ($IS_MENU_MINIMIZED) $IS_MENU_MINIMIZED = false
		}}>
			<i class="fas fa-magnifying-glass text-[1.6rem]" />
		</button>

		{#if showSearch}
			<input
				bind:value={searchTerm}
				autofocus
				class="min-w-[10rem] h-[4.5rem] px-[1rem] text-[1.6rem] bg-[color:var(--color-tertiary)]"
				type="text"
				placeholder="Search"
			/>
		{/if}
	</button>

	<div
		on:wheel={scrollHorizontally}
		bind:this={scrollableElement}
		class=" w-full  h-[5rem] items-end flex flex-row gap-2 overflow-y-visible overflow-x-scroll categories"
	>
		<button
			class="whitespace-nowrap w-fit px-10 h-[4.5rem] text-[1.6rem] bg-[color:var(--color-secondary)] grid place-items-center transition-all duration-200 ease-in-out"
			on:click={() => {
				selected = -1
				const allFurnitureItems = $FURNITURES.flatMap(furniture => furniture.items);
				$SHOWFURNITURES = { category: "All Objects", items: allFurnitureItems }
				if ($IS_MENU_MINIMIZED) $IS_MENU_MINIMIZED = false
			}}
			class:selected={selected === -1}>Tous les objets</button
		>
		{#each $FURNITURES as category, i}
			<button
				class=" whitespace-nowrap w-fit px-10 h-[4.5rem] text-[1.6rem] bg-[color:var(--color-secondary)] grid place-items-center transition-all duration-200 ease-in-out"
				on:click={() => {
					selected = i
					$SHOWFURNITURES = $FURNITURES[i]
					if ($IS_MENU_MINIMIZED) $IS_MENU_MINIMIZED = false
				}}
				class:selected={selected === i}>{category.category}</button
			>
		{/each}
	</div>

	<div class="overflow-y-visible flex flex-row gap-2 ml-auto">
		<button
			class="w-fit px-[2rem] items-center justify-center break h-[4.5rem] text-[1.6rem] bg-[color:var(--color-secondary)] flex flex-row gap-4 transition-all duration-200 ease-in-out"
			on:click={() => {
				$IS_CART_OPEN = false
				$IS_OWNEDITEMS_OPEN = !$IS_OWNEDITEMS_OPEN
				
			}}
			>
			<p class="w-fit whitespace-nowrap">Meubles achetés</p>
			<span class="h-fit px-[1rem] bg-[color:var(--color-tertiary)]"
				>{$OWNEDITEMS.length}</span
			>
		</button>
		<button
			class="h-[4.5rem] w-fit px-[2rem] text-[1.6rem] bg-[color:var(--color-secondary)] flex flex-row gap-4 items-center justify-center transition-all duration-200 ease-in-out"
			on:click={() => {
				$IS_OWNEDITEMS_OPEN = false
				$IS_CART_OPEN = !$IS_CART_OPEN
			}}
		>
			<i class="fas fa-shopping-cart" />
			<span
				class="h-fit px-[1rem] bg-[color:var(--color-tertiary)]"
				>{$CART.length}</span
			>
		</button>
		<button
			class="h-[4.5rem] w-fit aspect-square text-[1.6rem] bg-[color:var(--color-secondary)] flex flex-row gap-4 items-center justify-center transition-all duration-200 ease-in-out"
			on:click={() => {
				$IS_MENU_MINIMIZED = !$IS_MENU_MINIMIZED
			}}
		>
			<i class="fas fa-chevron-{$IS_MENU_MINIMIZED ? 'up' : 'down'}" />
		</button>
	</div>
</div>

<style>
	.selected {
		transform-origin: bottom;
		transform: scale(1.1);
		background-color: var(--color-primary);
		margin-right: 0.5rem;
		margin-left:  0.5rem;
	}

	.categories::-webkit-scrollbar {
		display: none;
	}
</style>

// react-ui/src/components/Header.tsx
import { useEffect, useRef, useState } from 'react';
import { useStore } from '@store/useStore';

export default function Header() {
  const furnitures = useStore((s) => s.furnitures);
  const setShowFurnitures = useStore((s) => s.setShowFurnitures);
  const isMenuMinimized = useStore((s) => s.isMenuMinimized);
  const setIsMenuMinimized = useStore((s) => s.setIsMenuMinimized);
  const cart = useStore((s) => s.cart);
  const ownedItems = useStore((s) => s.ownedItems);
  const isCartOpen = useStore((s) => s.isCartOpen);
  const setIsCartOpen = useStore((s) => s.setIsCartOpen);
  const isOwnedItemsOpen = useStore((s) => s.isOwnedItemsOpen);
  const setIsOwnedItemsOpen = useStore((s) => s.setIsOwnedItemsOpen);

  const [selected, setSelected] = useState(-1);
  const [showSearch, setShowSearch] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const scrollableRef = useRef<HTMLDivElement>(null);

  function scrollHorizontally(e: React.WheelEvent) {
    if (scrollableRef.current) {
      const delta = Math.max(-1, Math.min(1, (e as any).wheelDelta || -e.deltaY));
      scrollableRef.current.scrollLeft -= delta * 50;
      e.preventDefault();
    }
  }

  // Update shown furnitures when search or selection changes
  useEffect(() => {
    if (!furnitures) return;

    if (searchTerm.length > 0) {
      let allItems;
      if (selected === -1) {
        allItems = furnitures.flatMap((f) => f.items);
      } else {
        allItems = furnitures[selected].items;
      }
      const filtered = allItems.filter((f) =>
        f.label.toLowerCase().includes(searchTerm.toLowerCase())
      );
      setShowFurnitures({ category: 'Search Results', items: filtered });
    } else {
      if (selected === -1) {
        const allItems = furnitures.flatMap((f) => f.items);
        setShowFurnitures({ category: 'All Objects', items: allItems });
      } else {
        setShowFurnitures(furnitures[selected]);
      }
    }
  }, [searchTerm, selected, furnitures, setShowFurnitures]);

  return (
    <div className="w-full h-full overflow-y-visible flex flex-row gap-2 items-end flex-nowrap">
      {/* Search */}
      <button
        className={`h-[4.5rem] ${
          showSearch ? 'w-fit' : 'w-[5rem] aspect-square'
        } bg-[color:var(--color-secondary)] flex flex-row gap-2 items-center`}
      >
        <button
          className="h-[4.5rem] w-[4.5rem] aspect-square bg-[color:var(--color-secondary)] flex flex-row gap-2 items-center justify-center"
          onClick={() => {
            setShowSearch(!showSearch);
            if (isMenuMinimized) setIsMenuMinimized(false);
          }}
        >
          <i className="fas fa-magnifying-glass text-[1.6rem]" />
        </button>

        {showSearch && (
          <input
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            autoFocus
            className="min-w-[10rem] h-[4.5rem] px-[1rem] text-[1.6rem] bg-[color:var(--color-tertiary)]"
            type="text"
            placeholder="Search"
          />
        )}
      </button>

      {/* Category tabs */}
      <div
        onWheel={scrollHorizontally}
        ref={scrollableRef}
        className="w-full h-[5rem] items-end flex flex-row gap-2 overflow-y-visible overflow-x-scroll categories"
        style={{ scrollbarWidth: 'none' }}
      >
        <button
          className={`whitespace-nowrap w-fit px-10 h-[4.5rem] text-[1.6rem] bg-[color:var(--color-secondary)] grid place-items-center transition-all duration-200 ease-in-out ${
            selected === -1
              ? 'scale-110 origin-bottom bg-[color:var(--color-primary)] mx-2'
              : ''
          }`}
          onClick={() => {
            setSelected(-1);
            if (furnitures) {
              const allItems = furnitures.flatMap((f) => f.items);
              setShowFurnitures({ category: 'All Objects', items: allItems });
            }
            if (isMenuMinimized) setIsMenuMinimized(false);
          }}
        >
          React Tous les objets
        </button>
        {furnitures?.map((category, i) => (
          <button
            key={i}
            className={`whitespace-nowrap w-fit px-10 h-[4.5rem] text-[1.6rem] bg-[color:var(--color-secondary)] grid place-items-center transition-all duration-200 ease-in-out ${
              selected === i
                ? 'scale-110 origin-bottom bg-[color:var(--color-primary)] mx-2'
                : ''
            }`}
            onClick={() => {
              setSelected(i);
              setShowFurnitures(furnitures[i]);
              if (isMenuMinimized) setIsMenuMinimized(false);
            }}
          >
            {category.category}
          </button>
        ))}
      </div>

      {/* Right buttons */}
      <div className="overflow-y-visible flex flex-row gap-2 ml-auto">
        <button
          className="w-fit px-[2rem] items-center justify-center break h-[4.5rem] text-[1.6rem] bg-[color:var(--color-secondary)] flex flex-row gap-4 transition-all duration-200 ease-in-out"
          onClick={() => {
            setIsCartOpen(false);
            setIsOwnedItemsOpen(!isOwnedItemsOpen);
          }}
        >
          <p className="w-fit whitespace-nowrap">Meubles achetés</p>
          <span className="h-fit px-[1rem] bg-[color:var(--color-tertiary)]">
            {ownedItems.length}
          </span>
        </button>
        <button
          className="h-[4.5rem] w-fit px-[2rem] text-[1.6rem] bg-[color:var(--color-secondary)] flex flex-row gap-4 items-center justify-center transition-all duration-200 ease-in-out"
          onClick={() => {
            setIsOwnedItemsOpen(false);
            setIsCartOpen(!isCartOpen);
          }}
        >
          <i className="fas fa-shopping-cart" />
          <span className="h-fit px-[1rem] bg-[color:var(--color-tertiary)]">
            {cart.length}
          </span>
        </button>
        <button
          className="h-[4.5rem] w-fit aspect-square text-[1.6rem] bg-[color:var(--color-secondary)] flex flex-row gap-4 items-center justify-center transition-all duration-200 ease-in-out"
          onClick={() => setIsMenuMinimized(!isMenuMinimized)}
        >
          <i
            className={`fas fa-chevron-${isMenuMinimized ? 'up' : 'down'}`}
          />
        </button>
      </div>
    </div>
  );
}
