// react-ui/src/components/OwnedItems.tsx
import { useStore } from '@store/useStore';
import { sendNUI } from '@utils/sendNUI';

export default function OwnedItems() {
  const isOwnedItemsOpen = useStore((s) => s.isOwnedItemsOpen);
  const setIsOwnedItemsOpen = useStore((s) => s.setIsOwnedItemsOpen);
  const ownedItems = useStore((s) => s.ownedItems);

  if (!isOwnedItemsOpen) return null;

  return (
    <div className="w-[40rem] h-[60rem] bg-[color:var(--color-primary)] absolute right-0 -top-[65rem] flex flex-col gap-[1rem]">
      <div className="flex flex-row gap-2">
        <h1 className="bg-[color:var(--color-secondary)] text-[2rem] py-4 w-full h-fit text-center">
          Meubles achetés
        </h1>
        <button
          className="bg-[color:var(--color-secondary)] text-[2rem] py-4 h-full text-center aspect-square"
          onClick={() => setIsOwnedItemsOpen(false)}
        >
          <i className="fa-solid fa-xmark" />
        </button>
      </div>
      <div className="flex flex-col gap-2 px-4 overflow-scroll h-full scroll-style scroll-style-vertical">
        {ownedItems.map((item: any, i) => (
          <div
            key={i}
            className="flex flex-row gap-2 w-full justify-between bg-[color:var(--color-secondary)] p-4 items-center"
          >
            <button
              className="bg-[color:var(--color-tertiary)] text-[2rem] w-[4rem] h-[4rem] text-center aspect-square"
              onClick={() => {
                sendNUI('selectOwnedItem', item);
              }}
            >
              <i className="fa-solid fa-magnifying-glass" />
            </button>
            <div className="flex flex-col gap-2 w-full">
              <h1 className="text-[2rem]">{item.label}</h1>
            </div>
            <button
              className="bg-[color:var(--color-tertiary)] text-[2rem] py-4 h-full text-center aspect-square"
              onClick={() => {
                sendNUI('removeOwnedItem', item);
              }}
            >
              <i className="fa-solid fa-xmark" />
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}

// ui/src/components/OwnedItems.svelte
<script lang="ts">
	import { IS_OWNEDITEMS_OPEN, OWNEDITEMS } from "@store/stores"
    import { SendNUI } from "@utils/SendNUI";
</script>




{#if $IS_OWNEDITEMS_OPEN}
	<div
		class="w-[40rem] h-[60rem] bg-[color:var(--color-primary)] absolute right-0 -top-[65rem] flex flex-col gap-[1rem]"
	>
		<div class="flex flex-row gap-2">
			<h1
				class="bg-[color:var(--color-secondary)] text-[2rem] py-4 w-full h-fit text-center"
			>
				Meubles achetés
			</h1>
			<button
				class="bg-[color:var(--color-secondary)] text-[2rem] py-4 h-full text-center aspect-square"
				on:click={() => ($IS_OWNEDITEMS_OPEN = false)}
			>
				<i class="fa-solid fa-xmark" />
			</button>
		</div>
		<div
			class="flex flex-col gap-2 px-4 overflow-scroll h-full scroll-style scroll-style-vertical"
		>
			{#each $OWNEDITEMS as item, i}
				<div
					class="flex flex-row gap-2 w-full justify-between bg-[color:var(--color-secondary)] p-4 items-center"
				>
					<button
						class="bg-[color:var(--color-tertiary)] text-[2rem] w-[4rem] h-[4rem] text-center aspect-square"
						on:click={() => {
							SendNUI('selectOwnedItem', item)
						}}
					>
						<i class="fa-solid fa-magnifying-glass" />
					</button>
					<div class="flex flex-col gap-2 w-full">
						<h1 class="text-[2rem]">{item.label}</h1>
					</div>
					<button
						class="bg-[color:var(--color-tertiary)] text-[2rem] py-4 h-full text-center aspect-square"
						on:click={() => {
							SendNUI('removeOwnedItem', item)
						}}
					>
						<i class="fa-solid fa-xmark" />
					</button>
				</div>
			{/each}
		</div>
	</div>
{/if}
